Repository novareach-solutions/movemate, pull requests merged in 2024-12, with the labels that each got.

#49 Implement User Module with CRUD Operations and Integration with Database
  .gitignore
  apps/backend/docker-compose.yml
  apps/backend/src/modules/user/user.controller.ts
  apps/backend/src/modules/user/user.module.ts
  apps/backend/src/modules/user/user.service.ts
  apps/backend/src/modules/user/user.types.ts
Labels: enhancement

#56 feat: Create entity for send a package
  apps/backend/backend-main/src/entity/DropLocation.ts
  apps/backend/backend-main/src/entity/Order.ts
  apps/backend/backend-main/src/entity/OrderReview.ts
  apps/backend/backend-main/src/entity/PickupLocation.ts
  apps/backend/backend-main/src/entity/Report.ts
  apps/backend/backend-main/src/entity/SendAPackage.ts
  apps/backend/backend-main/src/migration/1733233728082-sendapackageentity.ts
  apps/backend/backend-main/src/shared/enums.ts
Labels: enhancement

#65 Send A Package Entity
  apps/backend/backend-main/src/entity/DropLocation.ts
  apps/backend/backend-main/src/entity/Order.ts
  apps/backend/backend-main/src/entity/OrderReview.ts
  apps/backend/backend-main/src/entity/PickupLocation.ts
  apps/backend/backend-main/src/entity/Report.ts
  apps/backend/backend-main/src/entity/SendPackageOrder.ts
  apps/backend/backend-main/src/migration/1733694953013-SendAPackageEntity.ts
  apps/backend/backend-main/src/shared/enums.ts
Labels: Feature

#46 GitHub Workflow for the entire project & workspaces introduced
  .github/workflow/backend.yml
  .github/workflow/frontend.yml
  .gitignore
  apps/backend/backend-main/package.json
  apps/frontend/web/admin/.gitignore
  apps/frontend/web/admin/package.json
  package.json
  shared/core/package.json
  yarn.lock
Labels: enhancement

#60 Add Linting and Prettier Validation for All Applications in the Monorepo
  .husky/pre-commit
  apps/backend/backend-main/README.md
  apps/backend/backend-main/src/entity/DropLocation.ts
  apps/backend/backend-main/src/entity/PickupLocation.ts
  apps/backend/backend-main/src/entity/Report.ts
  apps/backend/backend-main/src/entity/SendPackageOrder.ts
  apps/backend/backend-main/src/logger.ts
  apps/backend/backend-main/src/migration/1733694953013-SendAPackageEntity.ts
  apps/backend/backend-main/src/modules/agent/agent.controller.ts
  apps/backend/backend-main/src/modules/agent/agent.service.ts
  apps/backend/backend-main/src/modules/auth/auth.controller.ts
  apps/backend/backend-main/src/modules/auth/auth.service.ts
  apps/backend/backend-main/src/modules/auth/utils/crypto.ts
  apps/backend/backend-main/src/modules/auth/utils/generateTokens.ts
  apps/backend/backend-main/src/modules/database/database.service.ts
  apps/backend/backend-main/src/modules/redis/redis.module.ts
  apps/backend/backend-main/src/modules/redis/redis.service.ts
  apps/backend/backend-main/src/modules/user/user.controller.ts
  apps/backend/backend-main/src/modules/user/user.service.ts
  apps/backend/backend-main/src/shared/enums.ts
  apps/backend/backend-main/src/shared/errors/userFacing.ts
  apps/backend/backend-main/src/shared/gateways/agent.notification.gateway.ts
  apps/backend/backend-main/src/shared/gateways/base.socket.ts
  apps/backend/backend-main/src/shared/gateways/chat.support.gateway.ts
  apps/backend/backend-main/src/shared/gateways/customer.notification.gateway.ts
  apps/backend/backend-main/src/shared/gateways/notification.gateway.ts
  apps/backend/backend-main/src/shared/guards/auth.guard.ts
  apps/backend/backend-main/src/shared/guards/onboarding.guard.ts
  apps/backend/backend-main/src/shared/guards/roles.guard.ts
  apps/backend/backend-main/test/app.e2e-spec.ts
  apps/frontend/web/admin/src/pages/_app.tsx
  apps/frontend/web/admin/src/pages/_document.tsx
  apps/frontend/web/admin/src/pages/api/hello.ts
  apps/frontend/web/admin/src/pages/index.tsx
  apps/frontend/web/admin/tailwind.config.ts
  package.json
Labels: enhancement, Feature

#54 Integrate Stripe Payment Processing and Customer Management
  apps/backend/backend-main/docker-compose.yml
  apps/backend/backend-main/sample.env
  apps/backend/backend-main/src/app.module.ts
  apps/backend/backend-main/src/entity/DropLocation.ts
  apps/backend/backend-main/src/entity/Order.ts
  apps/backend/backend-main/src/entity/OrderReview.ts
  apps/backend/backend-main/src/entity/PickupLocation.ts
  apps/backend/backend-main/src/modules/stripe/stripe.controller.ts
  apps/backend/backend-main/src/modules/stripe/stripe.module.ts
  apps/backend/backend-main/src/modules/stripe/stripe.service.ts
  apps/backend/backend-main/src/shared/enums.ts
  apps/backend/backend-main/src/shared/errors/stripe.ts
  apps/backend/backend-main/yarn.lock
  package.json
Labels: enhancement

#74 refactor: Auth logic refactored, working auth and user module
  apps/backend/backend-main/package.json
  apps/backend/backend-main/src/app.module.ts
  apps/backend/backend-main/src/entity/Agent.ts
  apps/backend/backend-main/src/entity/AgentDocument.ts
  apps/backend/backend-main/src/entity/RequiredDocument.ts
  apps/backend/backend-main/src/errorFilter.ts
  apps/backend/backend-main/src/main.ts
  apps/backend/backend-main/src/modules/agent/agent.controller.ts
  apps/backend/backend-main/src/modules/agent/agent.module.ts
  apps/backend/backend-main/src/modules/agent/agent.service.ts
  apps/backend/backend-main/src/modules/agent/agent.types.ts
  apps/backend/backend-main/src/modules/auth/auth.controller.ts
  apps/backend/backend-main/src/modules/auth/auth.module.ts
  apps/backend/backend-main/src/modules/auth/auth.service.ts
  apps/backend/backend-main/src/modules/auth/utils/generateTokens.ts
  apps/backend/backend-main/src/modules/user/user.controller.ts
  apps/backend/backend-main/src/modules/user/user.module.ts
  apps/backend/backend-main/src/modules/user/user.service.ts
  apps/backend/backend-main/src/shared/enums.ts
  apps/backend/backend-main/src/shared/guards/auth.guard.ts
  apps/backend/backend-main/src/shared/interface.ts
  apps/backend/backend-main/yarn.lock
Labels: enhancement

#85 Backend eslint configurations fix
  apps/backend/backend-main/eslint.config.mjs
  apps/backend/backend-main/src/app.module.ts
  apps/backend/backend-main/src/entity/Agent.ts
  apps/backend/backend-main/src/entity/AgentDocument.ts
  apps/backend/backend-main/src/entity/RequiredDocument.ts
  apps/backend/backend-main/src/errorFilter.ts
  apps/backend/backend-main/src/main.ts
  apps/backend/backend-main/src/modules/agent/agent.controller.ts
  apps/backend/backend-main/src/modules/agent/agent.module.ts
  apps/backend/backend-main/src/modules/agent/agent.service.ts
  apps/backend/backend-main/src/modules/auth/auth.controller.ts
  apps/backend/backend-main/src/modules/auth/auth.module.ts
  apps/backend/backend-main/src/modules/user/user.controller.ts
  apps/backend/backend-main/src/modules/user/user.module.ts
  apps/backend/backend-main/src/modules/user/user.service.ts
  apps/backend/backend-main/src/shared/enums.ts
  apps/backend/backend-main/src/shared/gateways/agent.notification.gateway.ts
  apps/backend/backend-main/src/shared/gateways/base.socket.ts
  apps/backend/backend-main/src/shared/guards/auth.guard.ts
  apps/backend/backend-main/src/shared/interface.ts
  eslint.config.mjs
  package.json
Labels: bug

#89 feat: Media module
  apps/backend/backend-main/package.json
  apps/backend/backend-main/sample.env
  apps/backend/backend-main/src/modules/media/media.controller.ts
  apps/backend/backend-main/src/modules/media/media.module.ts
  apps/backend/backend-main/src/modules/media/media.service.ts
  apps/backend/backend-main/src/shared/errors/media.ts
  yarn.lock
Labels: Feature

#91 Feat: Updating location of agent and notifying when a new order is placed
  apps/backend/backend-main/src/modules/agent/agent.controller.ts
  apps/backend/backend-main/src/modules/agent/agent.service.ts
  apps/backend/backend-main/src/modules/agent/agents.constants.ts
  apps/backend/backend-main/src/modules/redis/redis.service.ts
  apps/backend/backend-main/src/shared/enums.ts
  apps/backend/backend-main/src/shared/gateways/agent.notification.gateway.ts
Labels: Feature

#88 feat: Add comprehensive Swagger/OpenAPI documentation for all working API endpoints
  .husky/pre-commit
  apps/backend/backend-main/src/app.controller.spec.ts
  apps/backend/backend-main/src/app.controller.ts
  apps/backend/backend-main/src/main.ts
  apps/backend/backend-main/src/modules/agent/agent.controller.ts
  apps/backend/backend-main/src/modules/agent/dto/agent.dto.ts
  apps/backend/backend-main/src/modules/auth/auth.controller.ts
  apps/backend/backend-main/src/modules/auth/dto/auth.dto.ts
  apps/backend/backend-main/src/modules/user/dto/user.dto.ts
  apps/backend/backend-main/src/modules/user/user.controller.ts
  apps/backend/backend-main/src/utils/app.dto.ts
  apps/backend/backend-main/test/app.e2e-spec.ts
  apps/backend/backend-main/test/jest-e2e.json
Labels: Feature

#98 fix: Bug fix related to the agent service
  apps/backend/backend-main/package.json
  apps/backend/backend-main/src/modules/agent/agent.controller.ts
  apps/backend/backend-main/src/modules/agent/agent.module.ts
  apps/backend/backend-main/src/modules/agent/agent.service.ts
  apps/backend/backend-main/src/modules/agent/agents.constants.ts
  apps/backend/backend-main/src/modules/media/media.controller.ts
  apps/backend/backend-main/src/modules/media/media.module.ts
  apps/backend/backend-main/src/modules/media/media.service.ts
  apps/backend/backend-main/src/modules/redis/redis.service.ts
  apps/backend/backend-main/src/shared/enums.ts
  apps/backend/backend-main/src/shared/errors/media.ts
  yarn.lock
Labels: bug
