Repository novareach-solutions/movemate, pull requests merged in 2025-02, with the labels that each got.

#161 Refactor: Migrate from `process.env` to `ConfigService` for environment variable management
  apps/backend/backend-main/package.json
  apps/backend/backend-main/src/app.module.ts
  apps/backend/backend-main/src/config/app.config.ts
  apps/backend/backend-main/src/config/database.config.ts
  apps/backend/backend-main/src/config/jwt.config.ts
  apps/backend/backend-main/src/config/redis.config.ts
  apps/backend/backend-main/src/config/validation.ts
  apps/backend/backend-main/src/logger.ts
  apps/backend/backend-main/src/main.ts
Labels: bug, Improvement

#122 refactor: Controllers Refactored Swagger Decorators into Separate Files
  apps/backend/backend-main/package.json
  apps/backend/backend-main/src/app.module.ts
  apps/backend/backend-main/src/config/app.config.ts
  apps/backend/backend-main/src/config/database.config.ts
  apps/backend/backend-main/src/config/jwt.config.ts
  apps/backend/backend-main/src/config/redis.config.ts
  apps/backend/backend-main/src/config/validation.ts
  apps/backend/backend-main/src/errorFilter.ts
  apps/backend/backend-main/src/health/health.controller.ts
  apps/backend/backend-main/src/logger.ts
  apps/backend/backend-main/src/main.ts
  apps/backend/backend-main/src/modules/agent/agent.controller.ts
  apps/backend/backend-main/src/modules/agent/agent.service.ts
  apps/backend/backend-main/src/modules/auth/auth.controller.ts
  apps/backend/backend-main/src/modules/auth/auth.service.ts
  apps/backend/backend-main/src/modules/media/media.controller.ts
  apps/backend/backend-main/src/modules/media/media.service.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.controller.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.service.ts
  apps/backend/backend-main/src/modules/redis/redis.service.ts
  apps/backend/backend-main/src/modules/support/notification.service.ts
  apps/backend/backend-main/src/modules/support/support.controller.ts
  apps/backend/backend-main/src/modules/support/support.service.ts
  apps/backend/backend-main/src/modules/user/user.controller.ts
  apps/backend/backend-main/src/modules/user/user.service.ts
  apps/backend/backend-main/src/shared/decorators/agents/agent.decorators.ts
  apps/backend/backend-main/src/shared/decorators/auth/auth.decorators.ts
  apps/backend/backend-main/src/shared/decorators/health/health.decorators.ts
  apps/backend/backend-main/src/shared/decorators/user/user.decorators.ts
Labels: enhancement, Feature

#62 Implement Initial Payment Management Flows with Stripe Integration
  .vscode/settings.json
  apps/backend/backend-main/.env.example
  apps/backend/backend-main/package.json
  apps/backend/backend-main/src/app.module.ts
  apps/backend/backend-main/src/entity/Agent.ts
  apps/backend/backend-main/src/entity/AgentSubscription.ts
  apps/backend/backend-main/src/entity/OrderReview.ts
  apps/backend/backend-main/src/entity/Payment.ts
  apps/backend/backend-main/src/entity/SendPackageOrder.ts
  apps/backend/backend-main/src/entity/User.ts
  apps/backend/backend-main/src/migration/1736115389869-PaymentSetup.ts
  apps/backend/backend-main/src/modules/stripe/payment.service.ts
  apps/backend/backend-main/src/modules/stripe/stripe.controller.ts
  apps/backend/backend-main/src/modules/stripe/stripe.module.ts
  apps/backend/backend-main/src/modules/stripe/stripe.service.ts
  apps/backend/backend-main/src/shared/enums.ts
  apps/backend/backend-main/src/shared/types/payment.types.ts
Labels: Feature

#170 Rider-Customer Chat Module integeration
  apps/backend/backend-main/src/app.module.ts
  apps/backend/backend-main/src/entity/OrderChatMessage.ts
  apps/backend/backend-main/src/migration/1738207225265-VerifiedPhotoUrl.ts
  apps/backend/backend-main/src/modules/gateway/gateway.module.ts
  apps/backend/backend-main/src/modules/orderChat/orderChat.controller.ts
  apps/backend/backend-main/src/modules/orderChat/orderChat.module.ts
  apps/backend/backend-main/src/modules/orderChat/orderChat.service.ts
  apps/backend/backend-main/src/modules/redis/redis.service.ts
  apps/backend/backend-main/src/modules/user/user.controller.ts
  apps/backend/backend-main/src/modules/user/user.service.ts
  apps/backend/backend-main/src/shared/gateways/index.ts
  apps/backend/backend-main/src/shared/gateways/orderChat.gateway.ts
  apps/frontend/mobile/Rider/ios/Podfile
  apps/frontend/mobile/Rider/ios/Podfile.lock
  apps/frontend/mobile/Rider/ios/Rider.xcodeproj/project.pbxproj
  apps/frontend/mobile/Rider/ios/Rider/Info.plist
  apps/frontend/mobile/Rider/ios/Rider/PrivacyInfo.xcprivacy
  apps/frontend/mobile/Rider/package-lock.json
  apps/frontend/mobile/Rider/package.json
  apps/frontend/mobile/Rider/src/Screens/ChatScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/DeliverPackage/HomeScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/DropOffOrderDetailsScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/EarningDetailsScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/LoginScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/OtpScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/PickUpOrderDetailsScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/SignupNumberScreen.tsx
  apps/frontend/mobile/Rider/src/api/apiEndPoints.ts
  apps/frontend/mobile/Rider/src/components/ChatModule.tsx
  apps/frontend/mobile/Rider/src/components/Modals/ConfirmPhotoModal.tsx
  apps/frontend/mobile/Rider/src/components/Modals/DeliveryModal.tsx
  apps/frontend/mobile/Rider/src/components/Modals/ExpandedModal.tsx
  apps/frontend/mobile/Rider/src/components/Modals/Order/OrderModal.tsx
  apps/frontend/mobile/Rider/src/components/ProfileForm.tsx
  apps/frontend/mobile/Rider/src/redux/slices/authSlice.ts
  apps/frontend/mobile/Rider/src/theme/form.ts
  apps/frontend/mobile/Rider/src/utils/helpers.ts
  apps/frontend/mobile/Rider/src/utils/zod/Registration.ts
  apps/frontend/mobile/Rider/yarn.lock
Labels: Feature

#176 refact: Create a new migration file
  apps/backend/backend-main/src/entity/SendPackageOrder.ts
  apps/backend/backend-main/src/migration/1736115389869-PaymentSetup.ts
  apps/backend/backend-main/src/migration/1739299648694-SendAPackagEntity.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.service.ts
Labels: Feature

#172 feat: backend-main implementation of customer side notifications
  apps/backend/backend-main/package.json
  apps/backend/backend-main/src/app.module.ts
  apps/backend/backend-main/src/entity/Notification.ts
  apps/backend/backend-main/src/entity/SendPackageOrder.ts
  apps/backend/backend-main/src/entity/User.ts
  apps/backend/backend-main/src/migration/1739339154837-SendAPackage.ts
  apps/backend/backend-main/src/modules/notification/notification.controller.ts
  apps/backend/backend-main/src/modules/notification/notification.module.ts
  apps/backend/backend-main/src/modules/notification/notification.service.ts
  apps/backend/backend-main/src/modules/notification/types/notification.interface.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.module.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.service.ts
  apps/frontend/mobile/Rider/src/components/Modals/DeliveryModal.tsx
  apps/frontend/mobile/Rider/src/components/Modals/ExpandedModal.tsx
  apps/frontend/mobile/Rider/src/components/ProfileForm.tsx
Labels: Feature

#196 feat: single api for login and signup
  apps/backend/backend-main/src/modules/agent/agent.controller.ts
  apps/backend/backend-main/src/modules/agent/agent.service.ts
  apps/backend/backend-main/src/modules/auth/auth.controller.ts
  apps/backend/backend-main/src/modules/auth/auth.service.ts
Labels: Feature

#197 refact: agent online/offline status api
  apps/backend/backend-main/src/main.ts
  apps/backend/backend-main/src/migration/1739339154837-SendAPackage.ts
  apps/backend/backend-main/src/modules/agent/agent.controller.ts
  apps/backend/backend-main/src/modules/agent/agent.service.ts
  apps/backend/backend-main/src/modules/agent/agent.types.ts
  apps/backend/backend-main/src/modules/auth/auth.controller.ts
  apps/backend/backend-main/src/modules/auth/auth.service.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.service.ts
  apps/backend/backend-main/src/shared/enums.ts
  apps/backend/backend-main/src/shared/guards/onboarding.guard.ts
Labels: Feature

#199 feat: Saved Address Module
  apps/backend/backend-main/src/entity/SavedAddress.ts
  apps/backend/backend-main/src/modules/user/user.controller.ts
  apps/backend/backend-main/src/modules/user/user.service.ts
  apps/backend/backend-main/src/modules/user/user.types.ts
Labels: Feature
