Repository novareach-solutions/movemate, pull requests merged in 2025-01, with the labels that each got.

#100 fix:add AgentNotificationGateway in providers of sendpackagemodule
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.module.ts
Labels: bug

#87 health check implement in backend app
  .husky/pre-commit
  apps/backend/backend-main/package.json
  apps/backend/backend-main/src/app.controller.spec.ts
  apps/backend/backend-main/src/app.controller.ts
  apps/backend/backend-main/src/app.module.ts
  apps/backend/backend-main/src/app.service.ts
  apps/backend/backend-main/src/entity/DropLocation.ts
  apps/backend/backend-main/src/entity/OrderReview.ts
  apps/backend/backend-main/src/entity/PickupLocation.ts
  apps/backend/backend-main/src/entity/Report.ts
  apps/backend/backend-main/src/entity/SendPackageOrder.ts
  apps/backend/backend-main/src/main.ts
  apps/backend/backend-main/src/migration/1734971118507-SendPackageEntity.ts
  apps/backend/backend-main/src/modules/agent/agent.controller.ts
  apps/backend/backend-main/src/modules/agent/dto/agent.dto.ts
  apps/backend/backend-main/src/modules/auth/auth.controller.ts
  apps/backend/backend-main/src/modules/auth/dto/auth.dto.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.controller.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.module.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.service.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.types.ts
  apps/backend/backend-main/src/modules/support/support.controller.ts
  apps/backend/backend-main/src/modules/support/support.service.ts
  apps/backend/backend-main/src/modules/user/dto/user.dto.ts
  apps/backend/backend-main/src/modules/user/user.controller.ts
  apps/backend/backend-main/src/shared/decorators/roles.decorator.ts
  apps/backend/backend-main/src/shared/enums.ts
  apps/backend/backend-main/src/shared/errors/sendAPackage.ts
  apps/backend/backend-main/src/utils/app.dto.ts
  apps/backend/backend-main/test/app.e2e-spec.ts
  apps/backend/backend-main/test/jest-e2e.json
  package.json
  yarn.lock
Labels: bug, Feature

#108 fix: backend-main application bug fix, app start failing
  apps/backend/backend-main/package.json
  apps/backend/backend-main/src/app.module.ts
  apps/backend/backend-main/src/app.service.ts
  apps/backend/backend-main/src/health/health.controller.ts
  apps/backend/backend-main/src/health/health.module.ts
  apps/backend/backend-main/yarn.lock
  package-lock.json
  package.json
  yarn.lock
Labels: bug

#115 Fix TypeORM Migration Script Paths in package.json
  apps/backend/backend-main/package.json
Labels: bug

#120 fix: remove corrupting migration files
  apps/backend/backend-main/package.json
  apps/backend/backend-main/src/migration/1734971118507-SendPackageEntity.ts
  apps/backend/backend-main/src/migration/1735052977944-CustomerSupportChatTables.ts
  apps/backend/backend-main/src/migration/1735578712643-ChatModule.ts
  apps/backend/backend-main/src/migration/1736926450088-SendPackageEntity.ts
Labels: bug

#136 feat: Enums value change to varchar
  apps/backend/backend-main/src/entity/Agent.ts
  apps/backend/backend-main/src/entity/RequiredDocument.ts
  apps/backend/backend-main/src/entity/SendPackageOrder.ts
  apps/backend/backend-main/src/entity/User.ts
  apps/backend/backend-main/src/migration/1737437573647-SendPackageEntityRefactored.ts
Labels: bug

#143 feat: add headers, accessToken after user/agent is created
  apps/backend/backend-main/src/app.module.ts
  apps/backend/backend-main/src/main.ts
  apps/backend/backend-main/src/modules/agent/agent.controller.ts
  apps/backend/backend-main/src/modules/agent/agent.service.ts
  apps/backend/backend-main/src/modules/media/media.service.ts
  apps/backend/backend-main/src/modules/user/user.controller.ts
  apps/backend/backend-main/src/modules/user/user.service.ts
Labels: Feature

#138 feat: Profile screens and components
  apps/frontend/mobile/Rider/package-lock.json
  apps/frontend/mobile/Rider/src/Screens/Profile/AccountScreen/DocumentsScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/Profile/AccountScreen/ManageAccountScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/Profile/AccountScreen/index.tsx
  apps/frontend/mobile/Rider/src/Screens/Profile/EarningModeScreens/SubscriptionPlansScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/Profile/EarningModeScreens/index.tsx
  apps/frontend/mobile/Rider/src/Screens/Profile/InboxScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/Profile/ReferFriendScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/Profile/WalletScreen/PayoutScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/Profile/WalletScreen/index.tsx
  apps/frontend/mobile/Rider/src/Screens/Profile/index.tsx
  apps/frontend/mobile/Rider/src/assets/images/BankDetails.png
  apps/frontend/mobile/Rider/src/assets/images/BlackArrow.png
  apps/frontend/mobile/Rider/src/assets/images/CurrencyCoin.png
  apps/frontend/mobile/Rider/src/assets/images/Document.png
  apps/frontend/mobile/Rider/src/assets/images/Document1.png
  apps/frontend/mobile/Rider/src/assets/images/LightningIcon.png
  apps/frontend/mobile/Rider/src/assets/images/PayoutCalender.png
  apps/frontend/mobile/Rider/src/assets/images/ProfileAccount.png
  apps/frontend/mobile/Rider/src/assets/images/ProfileEarningMode.png
  apps/frontend/mobile/Rider/src/assets/images/ProfileEarnings.png
  apps/frontend/mobile/Rider/src/assets/images/ProfileInbox.png
  apps/frontend/mobile/Rider/src/assets/images/ProfileLogout.png
  apps/frontend/mobile/Rider/src/assets/images/ProfileReferFriend.png
  apps/frontend/mobile/Rider/src/assets/images/ProfileRewards.png
  apps/frontend/mobile/Rider/src/assets/images/ProfileWallet.png
  apps/frontend/mobile/Rider/src/assets/images/ReferPlaceholder.png
  apps/frontend/mobile/Rider/src/assets/images/Reuploadicon.png
  apps/frontend/mobile/Rider/src/assets/images/RewardCoin.png
  apps/frontend/mobile/Rider/src/assets/images/SuccessIcon.png
  apps/frontend/mobile/Rider/src/assets/images/Vehicle.png
  apps/frontend/mobile/Rider/src/assets/images/VisaIcon.png
  apps/frontend/mobile/Rider/src/assets/images/WhiteArrow.png
  apps/frontend/mobile/Rider/src/assets/images/benefitCheck.png
  apps/frontend/mobile/Rider/src/assets/images/images.ts
  apps/frontend/mobile/Rider/src/components/ChatModule.tsx
  apps/frontend/mobile/Rider/src/components/DetailRow.tsx
  apps/frontend/mobile/Rider/src/components/HelpButton.tsx
  apps/frontend/mobile/Rider/src/components/Modals/DeliveryModal.tsx
  apps/frontend/mobile/Rider/src/components/Modals/ExpandedModal.tsx
  apps/frontend/mobile/Rider/src/components/Onboarding.tsx
  apps/frontend/mobile/Rider/src/components/PlanCard.tsx
  apps/frontend/mobile/Rider/src/navigation/AppNavigator.tsx
  apps/frontend/mobile/Rider/src/navigation/ScreenNames.ts
  apps/frontend/mobile/Rider/src/theme/colors.ts
  apps/frontend/mobile/Rider/yarn.lock
Labels: Feature

#149 feat: Pass cookies in response Object in signups
  apps/backend/backend-main/src/app.module.ts
  apps/backend/backend-main/src/modules/agent/agent.controller.ts
  apps/backend/backend-main/src/modules/agent/agent.service.ts
  apps/backend/backend-main/src/modules/media/media.service.ts
  apps/backend/backend-main/src/modules/user/user.controller.ts
  apps/backend/backend-main/src/modules/user/user.module.ts
  apps/backend/backend-main/src/modules/user/user.service.ts
Labels: Feature

#127 feat: Implement NestJS Logger for Enhanced Application Observability
  apps/backend/backend-main/src/errorFilter.ts
  apps/backend/backend-main/src/main.ts
  apps/backend/backend-main/src/modules/agent/agent.controller.ts
  apps/backend/backend-main/src/modules/agent/agent.service.ts
  apps/backend/backend-main/src/modules/auth/auth.controller.ts
  apps/backend/backend-main/src/modules/auth/auth.service.ts
  apps/backend/backend-main/src/modules/media/media.controller.ts
  apps/backend/backend-main/src/modules/media/media.service.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.controller.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.service.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.types.ts
  apps/backend/backend-main/src/modules/redis/redis.service.ts
  apps/backend/backend-main/src/modules/support/notification.service.ts
  apps/backend/backend-main/src/modules/support/support.controller.ts
  apps/backend/backend-main/src/modules/support/support.service.ts
  apps/backend/backend-main/src/modules/user/user.controller.ts
  apps/backend/backend-main/src/modules/user/user.service.ts
Labels: enhancement, Improvement

#102 File Upload fix for s3, entites enum fix, admin side apis for required docs and agent docs, also agent assignement enhancements
  apps/backend/backend-main/src/app.module.ts
  apps/backend/backend-main/src/entity/Agent.ts
  apps/backend/backend-main/src/entity/AgentDocument.ts
  apps/backend/backend-main/src/entity/RequiredDocument.ts
  apps/backend/backend-main/src/entity/SendPackageOrder.ts
  apps/backend/backend-main/src/entity/SupportTicket.ts
  apps/backend/backend-main/src/entity/User.ts
  apps/backend/backend-main/src/migration/1736287083203-SendAPackage.ts
  apps/backend/backend-main/src/modules/agent/agent.controller.ts
  apps/backend/backend-main/src/modules/agent/agent.module.ts
  apps/backend/backend-main/src/modules/agent/agent.service.ts
  apps/backend/backend-main/src/modules/agent/agent.types.ts
  apps/backend/backend-main/src/modules/auth/auth.service.ts
  apps/backend/backend-main/src/modules/media/aws.module.ts
  apps/backend/backend-main/src/modules/media/media.module.ts
  apps/backend/backend-main/src/modules/media/media.service.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.controller.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.module.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.service.ts
  apps/backend/backend-main/src/modules/order/sendPackage/sendPackage.types.ts
  apps/backend/backend-main/src/modules/pricing/pricing.constants.ts
  apps/backend/backend-main/src/modules/pricing/pricing.controller.ts
  apps/backend/backend-main/src/modules/pricing/pricing.module.ts
  apps/backend/backend-main/src/modules/pricing/pricing.service.ts
  apps/backend/backend-main/src/modules/pricing/pricing.type.ts
  apps/backend/backend-main/src/modules/redis/redis.service.ts
  apps/backend/backend-main/src/modules/stripe/stripe.controller.ts
  apps/backend/backend-main/src/modules/support/notification.service.ts
  apps/backend/backend-main/src/modules/support/support.controller.ts
  apps/backend/backend-main/src/modules/support/support.service.ts
  apps/backend/backend-main/src/modules/user/user.controller.ts
  apps/backend/backend-main/src/modules/user/user.module.ts
  apps/backend/backend-main/src/modules/user/user.service.ts
  apps/backend/backend-main/src/shared/errors/pricing.ts
  apps/backend/backend-main/src/shared/errors/user.ts
  apps/backend/backend-main/src/shared/gateways/agent.notification.gateway.ts
  apps/backend/backend-main/src/shared/gateways/base.socket.ts
  apps/backend/backend-main/src/shared/gateways/chat.support.gateway.ts
  apps/backend/backend-main/src/shared/gateways/customer.notification.gateway.ts
  apps/backend/backend-main/src/shared/interceptors/file-to-url.interceptor.ts
  apps/backend/backend-main/src/utils/timeFns.ts
  apps/frontend/mobile/Rider/src/Screens/DeliverPackage/HomeScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/FaqScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/Profile/EarningModeScreens/index.tsx
  apps/frontend/mobile/Rider/src/Screens/Profile/index.tsx
  apps/frontend/mobile/Rider/src/components/Header.tsx
  apps/frontend/mobile/Rider/src/components/Onboarding.tsx
  apps/frontend/mobile/Rider/src/navigation/ScreenNames.ts
Labels: enhancement

#104 feat: Price estimation module
  apps/backend/backend-main/src/modules/pricing/pricing.controller.ts
Labels: Feature

#147 Refactor: pixel perfect the rider flow
  apps/frontend/mobile/Rider/src/Screens/ComingSoon.tsx
  apps/frontend/mobile/Rider/src/Screens/Profile/AccountScreen/ReplaceVehicleScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/Profile/AccountScreen/index.tsx
  apps/frontend/mobile/Rider/src/Screens/Profile/InboxScreen.tsx
  apps/frontend/mobile/Rider/src/Screens/Profile/index.tsx
  apps/frontend/mobile/Rider/src/assets/images/Car.png
  apps/frontend/mobile/Rider/src/assets/images/Trophy.png
  apps/frontend/mobile/Rider/src/assets/images/images.ts
  apps/frontend/mobile/Rider/src/components/ImageText.tsx
  apps/frontend/mobile/Rider/src/navigation/AppNavigator.tsx
  apps/frontend/mobile/Rider/src/navigation/ScreenNames.ts
  apps/frontend/mobile/Rider/src/theme/colors.ts
Labels: Feature
